import { DishCategory, MeasurementUnit } from '@/constants/enums';
import { CreateRecipeInput } from '../schema/recipe';

export interface SeedRecipe extends CreateRecipeInput {
  imageUri: string;
}

export const DEFAULT_RECIPES: SeedRecipe[] = [
  {
    title: 'Classic Pancakes',
    servings: 4,
    category: DishCategory.BREAKFAST,
    prepTime: 10,
    cookTime: 15,
    tags: ['American', 'Quick', 'Kid-friendly'],
    imageUri: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800',
    ingredients: [
      { name: 'All-purpose flour', quantity: 1.5, unit: MeasurementUnit.CUP },
      { name: 'Milk', quantity: 1.25, unit: MeasurementUnit.CUP },
      { name: 'Egg', quantity: 1, unit: MeasurementUnit.UNIT },
      { name: 'Butter, melted', quantity: 3, unit: MeasurementUnit.TBSP },
      { name: 'Sugar', quantity: 2, unit: MeasurementUnit.TBSP },
      { name: 'Baking powder', quantity: 2, unit: MeasurementUnit.TSP },
      { name: 'Salt', quantity: 0.5, unit: MeasurementUnit.TSP },
    ],
    steps: [
      'In a large bowl, whisk together flour, sugar, baking powder, and salt.',
      'In a separate bowl, beat the egg, then add milk and melted butter.',
      'Pour the wet ingredients into the dry ingredients and stir until just combined. A few lumps are okay.',
      'Heat a non-stick pan or griddle over medium heat. Lightly grease if needed.',
      'Pour about 1/4 cup of batter for each pancake onto the hot surface.',
      'Cook until bubbles form on the surface and edges look set, about 2-3 minutes.',
      'Flip and cook for another 1-2 minutes until golden brown.',
      'Serve warm with maple syrup, butter, or your favorite toppings.',
    ],
  },
  {
    title: 'Caprese Salad',
    servings: 2,
    category: DishCategory.LUNCH,
    prepTime: 10,
    cookTime: 0,
    tags: ['Italian', 'Vegetarian', 'No-Cook', 'Healthy'],
    imageUri: 'https://images.unsplash.com/photo-1592417817098-8fd3d9eb14a5?w=800',
    ingredients: [
      { name: 'Fresh mozzarella', quantity: 8, unit: MeasurementUnit.OZ },
      { name: 'Ripe tomatoes', quantity: 2, unit: MeasurementUnit.UNIT },
      { name: 'Fresh basil leaves', quantity: 1, unit: MeasurementUnit.BUNCH },
      { name: 'Extra virgin olive oil', quantity: 2, unit: MeasurementUnit.TBSP },
      { name: 'Balsamic glaze', quantity: 1, unit: MeasurementUnit.TBSP },
      { name: 'Salt', quantity: 0.25, unit: MeasurementUnit.TSP },
      { name: 'Black pepper', quantity: 0.25, unit: MeasurementUnit.TSP },
    ],
    steps: [
      'Slice the mozzarella and tomatoes into 1/4-inch thick rounds.',
      'Arrange alternating slices of tomato and mozzarella on a serving plate, overlapping slightly.',
      'Tuck fresh basil leaves between the slices.',
      'Drizzle with extra virgin olive oil.',
      'Add balsamic glaze in a zigzag pattern.',
      'Season with salt and freshly ground black pepper.',
      'Serve immediately at room temperature for best flavor.',
    ],
  },
  {
    title: 'One-Pan Lemon Herb Chicken',
    servings: 4,
    category: DishCategory.DINNER,
    prepTime: 15,
    cookTime: 35,
    tags: ['Mediterranean', 'Healthy', 'One-Pan', 'Meal Prep'],
    imageUri: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=800',
    ingredients: [
      { name: 'Chicken thighs, bone-in', quantity: 4, unit: MeasurementUnit.UNIT },
      { name: 'Baby potatoes, halved', quantity: 1, unit: MeasurementUnit.LB },
      { name: 'Lemon', quantity: 1, unit: MeasurementUnit.UNIT },
      { name: 'Garlic cloves, minced', quantity: 4, unit: MeasurementUnit.CLOVE },
      { name: 'Fresh rosemary', quantity: 2, unit: MeasurementUnit.TBSP },
      { name: 'Fresh thyme', quantity: 1, unit: MeasurementUnit.TBSP },
      { name: 'Olive oil', quantity: 3, unit: MeasurementUnit.TBSP },
      { name: 'Salt', quantity: 1, unit: MeasurementUnit.TSP },
      { name: 'Black pepper', quantity: 0.5, unit: MeasurementUnit.TSP },
    ],
    steps: [
      'Preheat oven to 425°F (220°C).',
      'In a small bowl, mix olive oil, minced garlic, rosemary, thyme, salt, and pepper.',
      'Place chicken thighs and halved potatoes in a large baking pan.',
      'Pour the herb oil mixture over the chicken and potatoes, tossing to coat evenly.',
      'Cut lemon in half. Squeeze juice over everything, then nestle lemon halves in the pan.',
      'Arrange chicken skin-side up on top of the potatoes.',
      'Roast for 35-40 minutes until chicken reaches 165°F (74°C) and skin is golden and crispy.',
      'Let rest for 5 minutes before serving. Garnish with fresh herbs if desired.',
    ],
  },
  {
    title: 'Chocolate Mug Cake',
    servings: 1,
    category: DishCategory.DESSERT,
    prepTime: 2,
    cookTime: 2,
    tags: ['Quick', 'Single Serving', 'Microwave', 'Chocolate'],
    imageUri: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=800',
    ingredients: [
      { name: 'All-purpose flour', quantity: 4, unit: MeasurementUnit.TBSP },
      { name: 'Sugar', quantity: 4, unit: MeasurementUnit.TBSP },
      { name: 'Cocoa powder', quantity: 2, unit: MeasurementUnit.TBSP },
      { name: 'Milk', quantity: 3, unit: MeasurementUnit.TBSP },
      { name: 'Vegetable oil', quantity: 2, unit: MeasurementUnit.TBSP },
      { name: 'Vanilla extract', quantity: 0.25, unit: MeasurementUnit.TSP },
      { name: 'Baking powder', quantity: 0.125, unit: MeasurementUnit.TSP },
      { name: 'Salt', quantity: null, unit: null },
    ],
    steps: [
      'In a microwave-safe mug, whisk together flour, sugar, cocoa powder, baking powder, and a pinch of salt.',
      'Add milk, vegetable oil, and vanilla extract. Mix until smooth with no lumps.',
      'Microwave on high for 60-90 seconds. The cake will rise and then settle.',
      'Check doneness - it should be set but slightly gooey in the center.',
      'Let cool for 1 minute (the mug will be hot!).',
      'Enjoy directly from the mug. Optional: top with whipped cream, ice cream, or chocolate chips.',
    ],
  },
];
