import { ShoppingListCategory } from '@/lib/db/schema/shopping-list';

const CATEGORY_KEYWORDS: Record<ShoppingListCategory, string[]> = {
  Produce: [
    'tomato',
    'onion',
    'garlic',
    'lettuce',
    'spinach',
    'carrot',
    'potato',
    'celery',
    'pepper',
    'bell pepper',
    'cucumber',
    'zucchini',
    'broccoli',
    'cauliflower',
    'cabbage',
    'kale',
    'arugula',
    'romaine',
    'asparagus',
    'green bean',
    'pea',
    'corn',
    'eggplant',
    'squash',
    'pumpkin',
    'sweet potato',
    'yam',
    'beet',
    'radish',
    'turnip',
    'parsnip',
    'leek',
    'shallot',
    'scallion',
    'green onion',
    'spring onion',
    'chive',
    'artichoke',
    'fennel',
    'bok choy',
    'brussels sprout',
    'apple',
    'banana',
    'orange',
    'lemon',
    'lime',
    'grapefruit',
    'berry',
    'strawberry',
    'blueberry',
    'raspberry',
    'blackberry',
    'grape',
    'cherry',
    'peach',
    'plum',
    'nectarine',
    'apricot',
    'mango',
    'pineapple',
    'watermelon',
    'melon',
    'cantaloupe',
    'honeydew',
    'papaya',
    'kiwi',
    'avocado',
    'pear',
    'fig',
    'pomegranate',
    'coconut',
    'date',
    'raisin',
    'cranberry',
    'mushroom',
    'portobello',
    'shiitake',
    'cremini',
    'oyster mushroom',
    'herb',
    'basil',
    'cilantro',
    'parsley',
    'thyme',
    'rosemary',
    'sage',
    'oregano',
    'mint',
    'dill',
    'tarragon',
    'chervil',
    'marjoram',
    'ginger',
    'turmeric',
    'lemongrass',
    'jalapeno',
    'serrano',
    'habanero',
    'poblano',
    'anaheim',
    'chili pepper',
  ],
  Dairy: [
    'milk',
    'cream',
    'half and half',
    'half-and-half',
    'heavy cream',
    'whipping cream',
    'sour cream',
    'creme fraiche',
    'crème fraîche',
    'cheese',
    'cheddar',
    'mozzarella',
    'parmesan',
    'parmigiano',
    'feta',
    'ricotta',
    'cottage cheese',
    'cream cheese',
    'goat cheese',
    'blue cheese',
    'gorgonzola',
    'brie',
    'camembert',
    'gruyere',
    'swiss cheese',
    'provolone',
    'monterey jack',
    'pepper jack',
    'colby',
    'american cheese',
    'gouda',
    'havarti',
    'muenster',
    'fontina',
    'manchego',
    'asiago',
    'romano',
    'pecorino',
    'mascarpone',
    'butter',
    'margarine',
    'ghee',
    'yogurt',
    'greek yogurt',
    'kefir',
    'buttermilk',
    'egg',
    'eggs',
  ],
  'Meat & Seafood': [
    'chicken',
    'turkey',
    'duck',
    'beef',
    'steak',
    'ground beef',
    'pork',
    'ham',
    'bacon',
    'sausage',
    'bratwurst',
    'kielbasa',
    'chorizo',
    'salami',
    'pepperoni',
    'prosciutto',
    'pancetta',
    'lamb',
    'veal',
    'venison',
    'bison',
    'rabbit',
    'fish',
    'salmon',
    'tuna',
    'cod',
    'halibut',
    'tilapia',
    'trout',
    'bass',
    'snapper',
    'mahi mahi',
    'swordfish',
    'mackerel',
    'sardine',
    'anchovy',
    'herring',
    'catfish',
    'shrimp',
    'prawn',
    'crab',
    'lobster',
    'scallop',
    'clam',
    'mussel',
    'oyster',
    'squid',
    'calamari',
    'octopus',
    'crawfish',
    'crayfish',
    'meat',
    'poultry',
    'seafood',
    'deli meat',
    'lunch meat',
    'hot dog',
    'frankfurter',
    'meatball',
    'ground turkey',
    'ground chicken',
    'ground pork',
    'pork chop',
    'pork loin',
    'pork tenderloin',
    'pork belly',
    'rib',
    'spare rib',
    'baby back rib',
    'brisket',
    'roast',
    'pot roast',
    'sirloin',
    'ribeye',
    'tenderloin',
    'filet mignon',
    'flank steak',
    'skirt steak',
    'strip steak',
    'chuck',
    'round',
    'chicken breast',
    'chicken thigh',
    'chicken leg',
    'chicken wing',
    'drumstick',
    'whole chicken',
  ],
  Pantry: [
    'flour',
    'all-purpose flour',
    'bread flour',
    'whole wheat flour',
    'cake flour',
    'almond flour',
    'coconut flour',
    'rice flour',
    'cornmeal',
    'cornstarch',
    'corn starch',
    'sugar',
    'brown sugar',
    'powdered sugar',
    'confectioners sugar',
    'granulated sugar',
    'cane sugar',
    'raw sugar',
    'turbinado',
    'honey',
    'maple syrup',
    'molasses',
    'agave',
    'corn syrup',
    'salt',
    'pepper',
    'black pepper',
    'white pepper',
    'sea salt',
    'kosher salt',
    'oil',
    'olive oil',
    'vegetable oil',
    'canola oil',
    'coconut oil',
    'sesame oil',
    'peanut oil',
    'avocado oil',
    'sunflower oil',
    'grapeseed oil',
    'rice',
    'white rice',
    'brown rice',
    'jasmine rice',
    'basmati rice',
    'arborio rice',
    'wild rice',
    'quinoa',
    'couscous',
    'bulgur',
    'farro',
    'barley',
    'oat',
    'oatmeal',
    'rolled oats',
    'steel cut oats',
    'pasta',
    'spaghetti',
    'linguine',
    'fettuccine',
    'penne',
    'rigatoni',
    'macaroni',
    'fusilli',
    'farfalle',
    'orzo',
    'lasagna',
    'noodle',
    'egg noodle',
    'rice noodle',
    'ramen',
    'udon',
    'soba',
    'bean',
    'black bean',
    'kidney bean',
    'pinto bean',
    'navy bean',
    'cannellini',
    'great northern bean',
    'lima bean',
    'garbanzo',
    'chickpea',
    'lentil',
    'split pea',
    'vinegar',
    'white vinegar',
    'apple cider vinegar',
    'balsamic vinegar',
    'red wine vinegar',
    'white wine vinegar',
    'rice vinegar',
    'sherry vinegar',
    'soy sauce',
    'tamari',
    'fish sauce',
    'oyster sauce',
    'hoisin sauce',
    'teriyaki sauce',
    'worcestershire sauce',
    'hot sauce',
    'sriracha',
    'tabasco',
    'ketchup',
    'mustard',
    'mayonnaise',
    'salsa',
    'tomato sauce',
    'tomato paste',
    'marinara',
    'pizza sauce',
    'pesto',
    'tahini',
    'hummus',
    'broth',
    'stock',
    'chicken broth',
    'beef broth',
    'vegetable broth',
    'bouillon',
    'canned tomato',
    'diced tomato',
    'crushed tomato',
    'tomato puree',
    'sun-dried tomato',
    'canned',
    'spice',
    'cinnamon',
    'nutmeg',
    'allspice',
    'clove',
    'ginger powder',
    'cumin',
    'coriander',
    'paprika',
    'smoked paprika',
    'cayenne',
    'chili powder',
    'curry powder',
    'turmeric powder',
    'cardamom',
    'fennel seed',
    'caraway',
    'mustard seed',
    'celery seed',
    'poppy seed',
    'sesame seed',
    'dried oregano',
    'dried basil',
    'dried thyme',
    'dried rosemary',
    'bay leaf',
    'vanilla',
    'vanilla extract',
    'almond extract',
    'cocoa',
    'cocoa powder',
    'chocolate',
    'chocolate chip',
    'baking powder',
    'baking soda',
    'yeast',
    'active dry yeast',
    'instant yeast',
    'cream of tartar',
    'gelatin',
    'nut',
    'almond',
    'walnut',
    'pecan',
    'cashew',
    'peanut',
    'pistachio',
    'hazelnut',
    'macadamia',
    'pine nut',
    'peanut butter',
    'almond butter',
    'nut butter',
    'breadcrumb',
    'panko',
    'cracker',
    'crouton',
    'tortilla chip',
    'potato chip',
    'popcorn',
    'cereal',
    'granola',
    'olive',
    'caper',
    'pickle',
    'relish',
    'jam',
    'jelly',
    'preserves',
    'marmalade',
    'dried fruit',
    'raisin',
    'cranberry',
    'apricot',
    'date',
    'fig',
    'prune',
    'coconut milk',
    'coconut cream',
    'evaporated milk',
    'condensed milk',
    'powdered milk',
  ],
  Frozen: [
    'frozen vegetable',
    'frozen fruit',
    'frozen berry',
    'frozen pea',
    'frozen corn',
    'frozen spinach',
    'frozen broccoli',
    'frozen pizza',
    'frozen dinner',
    'frozen meal',
    'ice cream',
    'frozen yogurt',
    'sorbet',
    'gelato',
    'popsicle',
    'frozen pie',
    'frozen waffle',
    'frozen pancake',
    'frozen french fry',
    'frozen potato',
    'frozen fish',
    'frozen shrimp',
    'frozen chicken',
    'tv dinner',
    'frozen burrito',
    'frozen dumpling',
    'frozen appetizer',
  ],
  Bakery: [
    'bread',
    'loaf',
    'baguette',
    'sourdough',
    'ciabatta',
    'focaccia',
    'brioche',
    'challah',
    'rye bread',
    'whole wheat bread',
    'white bread',
    'multigrain bread',
    'roll',
    'dinner roll',
    'kaiser roll',
    'bun',
    'hamburger bun',
    'hot dog bun',
    'slider bun',
    'english muffin',
    'bagel',
    'croissant',
    'danish',
    'pastry',
    'muffin',
    'scone',
    'biscuit',
    'cornbread',
    'tortilla',
    'flour tortilla',
    'corn tortilla',
    'pita',
    'naan',
    'flatbread',
    'wrap',
    'lavash',
    'cake',
    'cupcake',
    'brownie',
    'cookie',
    'pie',
    'tart',
    'cheesecake',
    'donut',
    'doughnut',
    'cinnamon roll',
    'crumb cake',
    'pound cake',
    'angel food cake',
    'sponge cake',
  ],
  Other: [],
};

export function classifyIngredient(ingredientName: string): ShoppingListCategory {
  const normalized = ingredientName.toLowerCase().trim();

  const categories: ShoppingListCategory[] = [
    'Produce',
    'Dairy',
    'Meat & Seafood',
    'Pantry',
    'Frozen',
    'Bakery',
  ];

  for (const category of categories) {
    const keywords = CATEGORY_KEYWORDS[category];
    for (const keyword of keywords) {
      if (normalized.includes(keyword) || normalized === keyword) {
        return category;
      }
    }
  }

  return 'Other';
}

export function getCategoryKeywords(
  category: ShoppingListCategory
): string[] {
  return [...CATEGORY_KEYWORDS[category]];
}

export function getAllCategories(): ShoppingListCategory[] {
  return [
    'Produce',
    'Dairy',
    'Meat & Seafood',
    'Pantry',
    'Frozen',
    'Bakery',
    'Other',
  ];
}

export function isValidCategory(category: string): category is ShoppingListCategory {
  return getAllCategories().includes(category as ShoppingListCategory);
}
